name: Sync Action into Veracode

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  sync:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    name: Sync Veracode SCA Repo
    steps:
      - name: Checkout veracode-sca repo
        uses: actions/checkout@v4
        with:
          path: veracode-sca

      - name: Checkout ghes-actions-integration repo
        uses: actions/checkout@v4
        with:
          repository: veracode-org1/ghes-actions-integration
          token: ${{ secrets.PAT_TOKEN }}
          path: ghes-actions-integration

      - name: Copy dist and action.yml files to ghes-actions-integration/actions/sca-scan folder
        run: |
          cp -r veracode-sca/dist ghes-actions-integration/actions/sca-scan/
          cp veracode-sca/action.yml ghes-actions-integration/actions/sca-scan/

      - name: Commit and push changes to ghes-actions-integration
        run: |
          cd ghes-actions-integration
          git config user.name "santhoshVC92"
          git config user.email "skesavan@veracode.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/veracode-org1/ghes-actions-integration.git
          git add actions
          git commit -m "Sync Veracode SCA dist and action.yml"
          git push
