name: Sync Action into Veracode
on:
  push:
    tags:
      - v**

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync Veracode SCA Repo
    steps:
      - name: Checkout veracode-sca repo
        uses: actions/checkout@v4
        with:
          path: veracode-sca

      - name: Checkout ghes-actions-integration repo
        uses: actions/checkout@v4
        with:
          repository: veracode-org1/ghes-actions-integration
          token: ${{ secrets.PAT_TOKEN }}
          path: ghes-actions-integration

      - name: Copy dist and action.yml files to ghes-actions-integration/actions/sca-scan folder
        run: |
          cp -r veracode-sca/dist ghes-actions-integration/actions/sca-scan/
          cp veracode-sca/action.yml ghes-actions-integration/actions/sca-scan/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_TOKEN }}
          path: ghes-actions-integration
          commit-message: "Sync Veracode SCA dist and action.yml"
          branch: sync-sca-${{ github.run_number }}
          base: main
          title: "Sync latest changes from veracode-sca repository"
          body: |
            This PR syncs the latest changes from veracode-sca repository.
            - Updated dist folder
            - Updated action.yml file
